apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  namespace: sks-demo
spec:
  selector:
    app: webapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort # Demo时使用NodePort方便访问
